/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurante.vista;

/**
 *
 * @author Loreley
 *
 */
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import restaurante.modelo.Pedido;
import restaurante.modelo.DetallePedido;
import restaurante.controlador.PedidoControlador;

public class FrmPedidos extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPedidos.class.getName());
    private PedidoControlador controlador = new PedidoControlador();
    private Pedido pedidoActual;
    private DefaultTableModel modeloDetalles;
    private DefaultTableModel modeloPedidos;

    /**
     * Creates new form FrmPedidos
     */
    public FrmPedidos() {
        initComponents();
        this.setTitle("Pedidos");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        modeloDetalles = (DefaultTableModel) tblDetalles.getModel();
        modeloDetalles.setRowCount(0);

        modeloPedidos = (DefaultTableModel) tblPedidos.getModel();
        modeloPedidos.setRowCount(0);

        txtEstado.setText("En preparación");
        txtEstado.setEditable(false);
        txtCodigo.setEditable(false);

    }

    private void actualizarTablaDetalles() {
        modeloDetalles.setRowCount(0);
        if (pedidoActual != null) {
            for (DetallePedido detalle : pedidoActual.getDetalles()) {
                modeloDetalles.addRow(new Object[]{
                    detalle.getProducto(),
                    detalle.getCantidad(),
                    detalle.getPrecio(),
                    detalle.calcularSubtotal()
                });
            }
        }
    }

    private void actualizarTablaPedidos() {
        modeloPedidos.setRowCount(0);
        List<Pedido> lista = controlador.listarPedidos();
        for (Pedido p : lista) {
            modeloPedidos.addRow(new Object[]{
                p.getCodigo(),
                p.getCliente(),
                p.getSucursal(),
                p.getCanal(),
                p.getEstado(),
                p.calcularTotal()
            });
        }
    }

    private void limpiarFormularioPedido() {
        pedidoActual = null;
        txtCodigo.setText("");
        txtCliente.setText("");
        txtSucursal.setText("");
        txtEstado.setText("En preparación");
        txtProducto.setText("");
        txtCantidad.setText("");
        txtPrecio.setText("");
        if (modeloDetalles != null) {
            modeloDetalles.setRowCount(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        txtSucursal = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        cbxCanal = new javax.swing.JComboBox<>();
        btnCrearPedido = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        pnlDetalle = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalles = new javax.swing.JTable();
        pnlAcciones = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnClonar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pnlPedidos = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(31, 45, 55));
        jPanel1.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Restaurante");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 140, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gestión de pedidos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("DATOS DEL PEDIDO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel4.setText("Código:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel5.setText("Cliente:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel6.setText("Sucursal:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel7.setText("Canal:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel8.setText("Estado:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        txtCodigo.addActionListener(this::txtCodigoActionPerformed);
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 150, 30));
        getContentPane().add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 150, 30));
        getContentPane().add(txtSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 150, 30));

        txtEstado.addActionListener(this::txtEstadoActionPerformed);
        getContentPane().add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 150, 30));

        cbxCanal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presencial", "virtual" }));
        getContentPane().add(cbxCanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 150, 30));

        btnCrearPedido.setBackground(new java.awt.Color(0, 153, 0));
        btnCrearPedido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCrearPedido.setText("Crear Pedido");
        btnCrearPedido.addActionListener(this::btnCrearPedidoActionPerformed);
        getContentPane().add(btnCrearPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, 30));

        btnLimpiar.setBackground(new java.awt.Color(204, 102, 0));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 90, 30));

        pnlDetalle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("DETALLE DEL PEDIDO");
        pnlDetalle.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 20));

        jLabel10.setText("Producto:");
        pnlDetalle.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        pnlDetalle.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 140, 30));

        jLabel11.setText("Cantidad:");
        pnlDetalle.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        pnlDetalle.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 140, 30));

        jLabel12.setText("Precio:");
        pnlDetalle.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));
        pnlDetalle.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 52, 150, 30));

        btnAgregar.setBackground(java.awt.SystemColor.activeCaptionBorder);
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregar.setText("Agregar Producto");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);
        pnlDetalle.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 140, 30));

        tblDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblDetalles);

        pnlDetalle.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 140));

        getContentPane().add(pnlDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 510, 320));

        pnlAcciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("ACCIONES");
        pnlAcciones.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 20));

        btnConfirmar.setBackground(new java.awt.Color(0, 102, 51));
        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar Pedido");
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);
        pnlAcciones.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 150, 40));

        btnClonar.setBackground(new java.awt.Color(0, 0, 51));
        btnClonar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClonar.setForeground(new java.awt.Color(255, 255, 255));
        btnClonar.setText("Clonar Pedido");
        btnClonar.addActionListener(this::btnClonarActionPerformed);
        pnlAcciones.add(btnClonar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 120, 40));

        jButton1.setBackground(new java.awt.Color(204, 0, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Eliminar Pedido");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        pnlAcciones.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, 40));

        getContentPane().add(pnlAcciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 520, 100));

        pnlPedidos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("PEDIDOS REGISTRADOS");
        pnlPedidos.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 190, -1));

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Cliente", "Sucursal", "Canal", "Estado", "Total"
            }
        ));
        jScrollPane2.setViewportView(tblPedidos);

        pnlPedidos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 450, 220));

        getContentPane().add(pnlPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 500, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void btnCrearPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPedidoActionPerformed
        // TODO add your handling code here:
        String cliente = txtCliente.getText().trim();
        String sucursal = txtSucursal.getText().trim();
        String canal = cbxCanal.getSelectedItem() != null ? cbxCanal.getSelectedItem().toString() : "Presencial";

        if (cliente.isEmpty() || sucursal.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete el cliente y la sucursal.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            patrones.abstractfactory.AbstractFactoryPedido fabrica;
            if (canal.equalsIgnoreCase("Virtual")) {
                fabrica = new patrones.abstractfactory.FactoryPedidoVirtual();
            } else {
                fabrica = new patrones.abstractfactory.FactoryPedidoPresencial();
            }

            pedidoActual = controlador.crearPedido(fabrica, cliente, sucursal, canal);

            txtCodigo.setText(pedidoActual.getCodigo());
            txtEstado.setText(pedidoActual.getEstado());

            JOptionPane.showMessageDialog(this, "Pedido creado correctamente. Ahora agregue productos.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearPedidoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if (pedidoActual == null) {
            JOptionPane.showMessageDialog(this, "Primero debe crear un pedido.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String prod = txtProducto.getText().trim();
        String cantStr = txtCantidad.getText().trim();
        String precioStr = txtPrecio.getText().trim();

        if (prod.isEmpty() || cantStr.isEmpty() || precioStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos del producto.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int cantidad = Integer.parseInt(cantStr);
            double precio = Double.parseDouble(precioStr);

            pedidoActual.agregarDetalle(prod, cantidad, precio);
            actualizarTablaDetalles();

            txtProducto.setText("");
            txtCantidad.setText("");
            txtPrecio.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La cantidad y el precio deben ser valores numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        try {
            controlador.confirmarPedido(pedidoActual);
            actualizarTablaPedidos();
            JOptionPane.showMessageDialog(this, "¡Pedido confirmado y registrado con éxito!");
            limpiarFormularioPedido();
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Validación", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnClonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClonarActionPerformed
        // TODO add your handling code here:
        int fila = tblPedidos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un pedido de la tabla inferior para clonar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String codigoSel = (String) tblPedidos.getValueAt(fila, 0);
            List<restaurante.modelo.Pedido> lista = controlador.listarPedidos();
            restaurante.modelo.Pedido original = null;
            for (restaurante.modelo.Pedido p : lista) {
                if (p.getCodigo().equals(codigoSel)) {
                    original = p;
                    break;
                }
            }

            if (original != null) {
                pedidoActual = controlador.clonarPedido(original);
                txtCodigo.setText(pedidoActual.getCodigo());
                txtCliente.setText(pedidoActual.getCliente());
                txtSucursal.setText(pedidoActual.getSucursal());
                txtEstado.setText(pedidoActual.getEstado());
                cbxCanal.setSelectedItem(pedidoActual.getCanal());
                actualizarTablaDetalles();
                JOptionPane.showMessageDialog(this, "Pedido clonado con éxito. Puede modificarlo y confirmarlo.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al clonar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnClonarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarFormularioPedido();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int fila = tblPedidos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione un pedido de la tabla.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar el pedido seleccionado?",
                "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        String codigo = (String) tblPedidos.getValueAt(fila, 0);
        controlador.eliminarPedido(codigo);
        actualizarTablaPedidos();
        JOptionPane.showMessageDialog(this, "Pedido eliminado correctamente.");

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPedidos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnClonar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnCrearPedido;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbxCanal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlAcciones;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JPanel pnlPedidos;
    private javax.swing.JTable tblDetalles;
    private javax.swing.JTable tblPedidos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtSucursal;
    // End of variables declaration//GEN-END:variables
}
